apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: cowshed

build:
  artifacts:
    - image: ghcr.io/cownetwork/cowshed
      context: .
      docker:
        buildArgs:
          MAVEN_USER: "{{.MVN_USER}}"
          MAVEN_PASS: "{{.MVN_PASS}}"
deploy:
  kubectl:
    manifests:
     - run/deployment.yaml
portForward:
  - resourceType: Deployment
    resourceName: cowshed
    namespace: minecraft-staging
    port: 25565
    localPort: 25565