name: cowshed
main: network.cow.mc.cowshed.CowshedPlugin
api-version: 1.16
version: 1.0.0
depend: [Messages, SpigotExtensions]

commands:
  sonic:
    permission: cow.cowshed.sonic
  fly:
    permission: cow.cowshed.fly
  build:
    permission: cow.cowshed.build
  spawn: {}
  npc: {}
  emote: {}
